name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-cluster-collibra-dev-public-vault-d912d33a.857b0cae.z1.hashicorp.cloud:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault-cluster-collibra-dev-public-vault-d912d33a.857b0cae.z1.hashicorp.cloud:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp
